In [1]:
import numpy as np
import sys

## 1. 基础

shape = [3,4,5]
- axis = 0, 压缩第 0 个维度==》[4,5]
- 其他值同理 

In [2]:
a = np.array([[1, 2, 3], [4., 5., 6.],[7, 8, 9]])
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
# got dimension
a.ndim

2

In [5]:
# get shape
a.shape

(3, 3)

In [6]:
# 元素个数
print(a.size)

# 每个元素所占内存，以字节为单位
print(a.itemsize)

# 总的占用内存
print(a.size * a.itemsize)
assert a.size * a.itemsize == a.nbytes

9
8
72


## 2. 获取、改变指定元素

In [7]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# get a specific element
print(a[1, 5])
assert a[1, 5]==a[1, -2]

13


In [9]:
# 取行
print(a[1,:])

[ 8  9 10 11 12 13 14]


In [10]:
# 取列
print(a[:,1])

[2 9]


In [11]:
# 切片 [start_index: end_index: stepsize]
print(a[0, 1:6:2])
print(a[:, 1:6:2]) 
print(a[1, 1:-1:1])

[2 4 6]
[[ 2  4  6]
 [ 9 11 13]]
[ 9 10 11 12 13]


In [12]:
# 赋值
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [13]:
a[0, 3: -1] = 0
print(a)

[[ 1  2  3  0  0  0  7]
 [ 8  9 10 11 12 20 14]]


In [14]:
b = a[:, 0: 6: 1].reshape((2, 2, 3))
print(b)

[[[ 1  2  3]
  [ 0  0  0]]

 [[ 8  9 10]
  [11 12 20]]]


In [15]:
print(b[:, 1, :])

[[ 0  0  0]
 [11 12 20]]


In [16]:
b[:, 1, :] = [[99, 99, 99], [88, 88, 88]]
print(b)

[[[ 1  2  3]
  [99 99 99]]

 [[ 8  9 10]
  [88 88 88]]]


## 3. 各种不同类型的 array

In [17]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.full((2, 3), 99, dtype="float32")

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [20]:
np.full_like(b, 99)

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [21]:
# 注意这里输入的不是 tuple
np.random.rand(4, 2)

array([[0.47098543, 0.2021142 ],
       [0.57541234, 0.624565  ],
       [0.73224522, 0.26597623],
       [0.84690626, 0.38672308]])

In [22]:
# 注意这里输入的是 tuple
np.random.sample((4, 2))

array([[0.12013417, 0.80028369],
       [0.9414037 , 0.50018199],
       [0.93179995, 0.6898124 ],
       [0.11038449, 0.16246875]])

In [23]:
np.random.randint(1, 3, size=(3, 3))

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [24]:
# 单位矩阵
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr1 = np.array([1, 2, 3])
r1 = np.repeat(arr1, 3, axis=0)
r2 = np.repeat(arr1, 3, axis=0).reshape((3, 3))

arr2 = arr1.reshape((1, 3))
r3 = np.repeat(arr2, 3, axis=0)

# 注意 r2 和 r3 是不一样的
print(r1)
print("*" *20)
print(r2)
print("*" *20)
print(r3)

[1 1 1 2 2 2 3 3 3]
********************
[[1 1 1]
 [2 2 2]
 [3 3 3]]
********************
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [26]:
# array 的融合
o = np.ones((5, 5))
print(o)
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

# 复制，避免修改元数据 o
res = np.copy(o)
res[1: 4, 1: 4] = z
print("*" *20)
print(res)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
********************
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 4. 数学计算

In [27]:
a = np.array([1, 2, 3 ,4])
print(a)

[1 2 3 4]


In [28]:
print(a + 2)
print(a - 1)
print(a * 2)
print(a / 2)

[3 4 5 6]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [29]:
print(a ** 2)

[ 1  4  9 16]


In [30]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [3]:
a = [1] * 10
print(a)
print(np.array(a))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1 1 1 1 1 1 1 1 1 1]


## 5. 矩阵计算

In [31]:
# 矩阵乘法
a = np.ones((2, 3))
b = 2 * np.ones((3, 2))
print(np.matmul(a, b))
print(np.matmul(b, a))

[[6. 6.]
 [6. 6.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [32]:
# 矩阵的秩
c = 3 * np.identity(3)
np.linalg.det(c)

27.0

## 6. 统计

In [3]:
stats = np.random.randint(10, size=(2, 3))
print(stats)

[[1 9 4]
 [5 5 4]]


In [34]:
print(np.min(stats))
print(np.max(stats))

# 每行的最大值
print(np.max(stats, axis=1))
# 每列的最大值
print(np.max(stats, axis=0))

1
9
[9 5]
[8 2 9]


In [35]:
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))


[13  3 13]
[18 11]


In [51]:
batch_size = 10
k = 3
d_loss = []
d_losses = []
for i in range(k):
    real_d_loss = np.random.randint(0,10, (1,))
    fake_d_loss = np.random.randint(0,10, (1,))
    d_loss.append(list(0.5 * np.add(real_d_loss, fake_d_loss)))     # shape=[3, 1]
    print("real_loss:{}, fake_loss:{}, loss:{}".format(real_d_loss, fake_d_loss, d_loss))
d_losses.append(list(np.average(d_loss, 0)))    # axis=0, 压缩第 0 维度
print(d_losses[0][0]) # shape=[1]

real_loss:[1], fake_loss:[9], loss:[[5.0]]
real_loss:[5], fake_loss:[3], loss:[[5.0], [4.0]]
real_loss:[4], fake_loss:[7], loss:[[5.0], [4.0], [5.5]]
4.833333333333333


## 7. reshape

In [36]:
before = np.ones((2, 6))
print(before)

after = before.reshape(2, 2, 3)
print(after)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


## 8. 从文件中提取数据

In [37]:
filedata = np.genfromtxt("files/data.txt", delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [38]:
print(filedata>5)
print(filedata[filedata>7])

[[False False False False False  True  True  True  True  True]
 [False False False False False  True  True  True  True  True]
 [False False False False False  True  True  True  True  True]
 [False False False False False  True  True  True  True  True]
 [False False False False False  True  True  True  True  True]]
[ 8  9 10  8  9 10  8  9 10  8  9 10  8  9 10]


In [39]:
print((filedata>5) & (filedata<10))

[[False False False False False  True  True  True  True False]
 [False False False False False  True  True  True  True False]
 [False False False False False  True  True  True  True False]
 [False False False False False  True  True  True  True False]
 [False False False False False  True  True  True  True False]]


In [40]:
# [第二行第三列，第三行第四列，第四行第五列]
print(filedata[[1,2,3], [2,3,4]])

[3 4 5]


## 9. shuffle


In [8]:
size = 100
print(size)

suffled_index = np.random.permutation(np.arange(size))
print(suffled_index)


100
[35 88 47 71 58 73 18 74 43 77 33 83 49  1 44 27 61 60  0 89 25 54 36 46
 51  3 97 21 94 95 52 57 62 82  5 29 50 63 38 10 19  6  4 31 68 24 93 75
 65 55 32 42 84 56 40 98 11 41 66 26 23 53 39  8 76 86 99 92 12  2 87  9
 14 13 37 78 16 28 79 48 81 20 96 91 80 45 59 70 64 67 69 85  7 72 15 22
 30 90 17 34]
